name: Lint and Unit Vitests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-vitest:
    name: Lint and Unit Vitests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code or main
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit
