name: Update Firefox Extension

on:
  push:
    tags:
      - v*.*.*
      - cifix*
      - unlisted_v*.*.*
  repository_dispatch:
    types: [trigger-firefox-extension-publish]

jobs:
  build-firefox-extension:
    name: Build Firefox extension artifact
    runs-on: ubuntu-latest
    if: github.repository_owner == 'namakeingo' || github.repository_owner == 'zpix1'
    outputs:
      tag: ${{ steps.get_version.outputs.tag }}
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full git history
          fetch-tags: true # Ensures tags are fetched

      - name: Build
        env:
          FIREFOX_name: "YouTube Anti Translate - mv3"
          FIREFOX_author: "zpix1; ported by namakeingo"
          FIREFOX_gecko_id: "youtube-anti-translate-mv3@namakeingo.co.uk"
          FIREFOX_gecko_strict_min_version: "109.0"
        run: |-
          cp -r app dist
          # Modify manifest.json using jq
          jq --arg name "$FIREFOX_name" --arg author "$FIREFOX_author" \
            '.name = $name | .author = $author' \
            dist/manifest.json > dist/manifest.tmp.json && mv dist/manifest.tmp.json dist/manifest.json
          # we archive the dist folder and include SHA commit as the last step
          zip -r firefox-extension.zip dist

      - name: Get version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r .version app/manifest.json)
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Archive firefox-extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: firefox-extension.zip

  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    if: github.repository_owner == 'namakeingo' || github.repository_owner == 'zpix1'
    needs: build-firefox-extension

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "18"
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: firefox-extension

      - name: Install web-ext cli
        run: |-
          npm install --global web-ext
          ls

      - name: Determine channel
        id: determine-channel
        run: |-
          if [[ "${GITHUB_REF##*/}" == unlisted_v* ]]; then
            echo "channel=unlisted" >> "$GITHUB_OUTPUT"
          else
            echo "channel=listed" >> "$GITHUB_OUTPUT"
          fi

      - name: Sign and upload step # max 10 min if human review is triggered
        id: sign_step
        continue-on-error: true
        run: |-
          unzip firefox-extension.zip -d .
          cd dist

          set +e  # disable fail-on-error to allow timeout exit code to be captured
          timeout 600 \
            web-ext sign --channel=${{ steps.determine-channel.outputs.channel }} \
            --api-key="${{ secrets.AMO_JWT_ISSUER }}" \
            --api-secret="${{ secrets.AMO_JWT_SECRET }}"
          status=$?
          set -e  # restore default fail-on-error behavior

          echo "status=$status" >> "$GITHUB_OUTPUT"

      - name: Set Firefox for Android compatibility & approval_notes
        # Also run on timeout of "Sign and upload step" so that we provide the
        # necessary information for the AMO review team
        if: steps.sign_step.outputs.status == '0' || steps.sign_step.outputs.status == '124'
        run: |
          npm install jsonwebtoken@9.0.2 dotenv@16.5.0
          node .github/workflows/scripts/mozilla_amo_version_patch.js
        env:
          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
          VERSION: ${{ needs.build-firefox-extension.outputs.version }}
          EXTENSION_SLUG: "youtube-anti-translate-mv3"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Archive signed Firefox extension
        uses: actions/upload-artifact@v4
        if: steps.sign_step.outputs.status == '0'
        with:
          name: youtube_anti_translate_mv3-signed.xpi
          path: dist/web-ext-artifacts/youtube_anti_translate_mv3-*.xpi

      - name: Update and Publish GitHub Release
        uses: ncipollo/release-action@v1
        if: steps.sign_step.outputs.status == '0'
        with:
          allowUpdates: true
          updateOnlyUnreleased: true
          tag: ${{ needs.build-firefox-extension.outputs.tag }}
          name: ${{ needs.build-firefox-extension.outputs.version }}
          omitBodyDuringUpdate: true
          draft: false
          artifacts: dist/web-ext-artifacts/youtube_anti_translate_mv3-*.xpi
