name: Playwright
on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, labeled, unlabeled]
    branches: [main]
  schedule:
    - cron: "0 0 * * 0,2,4" # Run at midnight UTC every Sunday and Tuesday and Thursday

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  playwright:
    name: YT Anti Translate Extension Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Require 'safe-to-test' label
        if: github.event_name == 'pull_request_target' && github.event.pull_request.author_association != 'COLLABORATOR' && github.event.pull_request.author_association != 'MEMBER' && github.event.pull_request.author_association != 'OWNER'
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "safe-to-test"
          add_comment: true

      - name: Checkout PR code or main
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.ref || 'main' }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run unit tests
        run: npm run test:unit
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Set up virtual display
        run: sudo apt-get update && sudo apt-get install -y xvfb
      - name: Run Playwright tests
        env:
          YOUTUBE_API_KEY: "${{ secrets.YOUTUBE_API_KEY }}"
          GOOGLE_USER: "${{ secrets.GOOGLE_USER }}"
          GOOGLE_PWD: "${{ secrets.GOOGLE_PWD }}"
          GOOGLE_OTP_SECRET: "${{ secrets.GOOGLE_OTP_SECRET }}"
        run: xvfb-run npx playwright test --headed
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: tests-screenshots
          path: images/tests/
          retention-days: 30
